version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Server=db;Database=TodoDb;User Id=SA;Password=Fitness32_;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container-compose
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Fitness32_
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
