services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-volume-persistance
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Fitness32_
    volumes:
      - sqlvolume:/var/opt/mssql
    shm_size: 1g

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnetapi
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User Id=SA;Password=Fitness32_;Encrypt=False;TrustServerCertificate=True;

volumes:
  sqlvolume:
